// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`

/// Encrypt bytes into the app secure-storage payload format.
Future<String> encryptSecretPayload({
  required List<int> plainBytes,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSecretEncryptSecretPayload(
  plainBytes: plainBytes,
  password: password,
  saltBase64: saltBase64,
);

/// Decrypt the app secure-storage payload format into plaintext bytes.
Future<Uint8List> decryptSecretPayload({
  required String payloadJson,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSecretDecryptSecretPayload(
  payloadJson: payloadJson,
  password: password,
  saltBase64: saltBase64,
);

/// Derive the base64-encoded password verifier used by Dart secure storage.
Future<String> deriveSecretPasswordVerifier({
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSecretDeriveSecretPasswordVerifier(
  password: password,
  saltBase64: saltBase64,
);
